//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EbayFetcher.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.1.0.0")]
    public sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://api.ebay.com/wsapi")]
        public string EbayFetcher_com_ebay_developer_EbayService_eBayAPIInterfaceService {
            get {
                return ((string)(this["EbayFetcher_com_ebay_developer_EbayService_eBayAPIInterfaceService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://svcs.ebay.com/services/search/FindingService/v1")]
        public string EbayFetcher_com_ebay_developer_FindingsService_FindingService {
            get {
                return ((string)(this["EbayFetcher_com_ebay_developer_FindingsService_FindingService"]));
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("MartinLp-COIN-PRD-e69e2c47f-e1373e76")]
        public string appId_prod {
            get {
                return ((string)(this["appId_prod"]));
            }
            set {
                this["appId_prod"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1e4ad515-31f3-4ca0-a83f-51ffef6afc90")]
        public string devId_prod {
            get {
                return ((string)(this["devId_prod"]));
            }
            set {
                this["devId_prod"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("PRD-69e2c47f15e1-7f88-4483-9030-8406")]
        public string certId_prod {
            get {
                return ((string)(this["certId_prod"]));
            }
            set {
                this["certId_prod"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"AgAAAA**AQAAAA**aAAAAA**EvEGWQ**nY+sHZ2PrBmdj6wVnY+sEZ2PrA2dj6ACkYunCpCFowSdj6x9nY+seQ**9rYDAA**AAMAAA**f0DtOMfE9IasnUn0kpkDKE1ECcJGEDBtSTQQZEHI8csQ4FoTQ7jvTy2RDgE0zG5I8dJochUfcvaUWofSxGZYofESmD80vx8FmIZlBTZrtMlB0Q/GBnmejXsqTNJe6RYSn9AGSMBjrWBQOEaNlDBSAZvlshjSN0+On5vEKs5OOuddp0QpWy8qX75Fbg/HNYCOi/No1guwFIgCxHu0rR9jQ0YY1BAmvmw2WZ4IrRK0zisDdIKh4PicnjAfBP7R4OX8bEODaU0Pv4mPFSu5XUBc2KrLZK6Ny4owBQAe5DLLUoNI4haLxAQphbCQbttTqiNREevOPSezF38H7twIyOawuYPAMWAsl4FRxF7OXqwRaFYP/5stL0Ay4m4FSyLaR03OWqqVZeLhOcHJROoY67P75tw7W5QoGLfUXHvaq1FOQ3yZhBdDLwzYcpWOUT5dVDDNHMBMPiymX85VOEN4qrtZs3MeuPiMvUZ/A2Ka+CytN6fEYNLDwQxVoxSt9lm88wEEmMbNjVQZCtUCk64S/sKAjEQ7aYDOLvU8xMXZa3Nj5gXlR3UKLKnR/MiHF8ut2OPqGxyP22kvyov/LM6IyU84e0zuBMGLIOqlTWrW4wmuEHPHwNKmLdhihcLWX0VYXZZEI0Z09NMGCGFbhRvy939vQDa2lGtL6/NY7q9kSPCEgYtbKuQwOGDpx+D2eM3H/4msEwtdnnOVTZnG951gdlAQPjzvURnSdCZ18ccvRQ6JROM3eY186D6MZQmIVWlw4P4o")]
        public string token_prod {
            get {
                return ((string)(this["token_prod"]));
            }
            set {
                this["token_prod"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("MartinLp-COIN-SBX-2090fc79c-348d53e3")]
        public string appId_sandbox {
            get {
                return ((string)(this["appId_sandbox"]));
            }
            set {
                this["appId_sandbox"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1e4ad515-31f3-4ca0-a83f-51ffef6afc90")]
        public string devId_sandbox {
            get {
                return ((string)(this["devId_sandbox"]));
            }
            set {
                this["devId_sandbox"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("PRD-69e2c47f15e1-7f88-4483-9030-8406")]
        public string certId_sandbox {
            get {
                return ((string)(this["certId_sandbox"]));
            }
            set {
                this["certId_sandbox"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"AgAAAA**AQAAAA**aAAAAA**0/4GWQ**nY+sHZ2PrBmdj6wVnY+sEZ2PrA2dj6wFk4GlAJeEowSdj6x9nY+seQ**qC0EAA**AAMAAA**ppggXK5HtvVSu70qVkF9dmUAk2530IjRZshROTBhVE8R0cw/yMld9mdQ33Pil0+jf4Lc7yi7E0e5YOIGYZO4IOUrJM8axAAGaekYFTEMc0AcjgR9/nOliKpRndsS+vrYkdxCp1fq1tMXWYYuieyoWV0q7W8pu0My33KqMuj13l3WWmQ++8/tk5qism7H/Qrws+IsHMkVfuOOtXq3XVAuBzlj0Sv4kGntslIJtQZcoiwF7eBMPvjqF9jYqELYTpuQUB5T6s9zvLDUDxjjsT77vU/PtFyGhSv3xNnhwzxnUxPKbnY4tUJ5g+WMIq+FdkO9O2VRQAV1zXcKTh+PleDjukpS1NOCpARmch9DU7XBapQoeIj1GFe/79P/8oSG3ILbvp20rr6B8SMVN1L98awbSxH+LKlLWEEGzmHgU0ebJBqd+eFRZKnwP/AvIkurC1YMbvFzNMo0+eJQkaFwmFHMME7oTQL9HrWkQa86tMc/x1X+fVHYciaf6geUF/9thlF/NPDl+ASP4MUEHzLxGN/5N2u9g3ougAOw3+Iq/sn1zJtPr4Lyy9lYDhQv+izVDPVMEknLw9h36qe4LgtofX/3BVla1ULs5PL21ASaLRVz17rklk8BnuMJm+Uub1W/Ys16Xt1OlMwMgi3wIomRWJE0vDKFidrZ6gy2YppxzwmzrndP33yHroNof89xtjtqVE7p8p1XPnoVrN7gvVWssVeCErRNVSaf7DFl7YGGlZH0pRwypclE25x4vxfOxtHISApe")]
        public string token_sandbox {
            get {
                return ((string)(this["token_sandbox"]));
            }
            set {
                this["token_sandbox"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("https://api.ebay.com/wsapi")]
        public string endPoint_prod {
            get {
                return ((string)(this["endPoint_prod"]));
            }
            set {
                this["endPoint_prod"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("https://api.sandbox.ebay.com/wsapi")]
        public string endPoint_sandbox {
            get {
                return ((string)(this["endPoint_sandbox"]));
            }
            set {
                this["endPoint_sandbox"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("183067")]
        public string idVirtualReality_prod {
            get {
                return ((string)(this["idVirtualReality_prod"]));
            }
            set {
                this["idVirtualReality_prod"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("183067")]
        public string idVirtualReality_sandbox {
            get {
                return ((string)(this["idVirtualReality_sandbox"]));
            }
            set {
                this["idVirtualReality_sandbox"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("https://svcs.ebay.com/services/search/FindingService/v1")]
        public string urlFindings_prod {
            get {
                return ((string)(this["urlFindings_prod"]));
            }
            set {
                this["urlFindings_prod"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://svcs.sandbox.ebay.com/services/search/FindingService/v1")]
        public string urlFindings_sandbox {
            get {
                return ((string)(this["urlFindings_sandbox"]));
            }
            set {
                this["urlFindings_sandbox"] = value;
            }
        }
    }
}
